sudo: false
language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
sudo: required
before_install:
    # See issue #80: litmus fails to build on travis
    # The branch 'travis-litmus' still has this enabled to investigate...
#    - sudo apt-get install libneon27-dev
#    - ./install_litmus.sh
install: pip install tox-travis
script: tox
