sudo: false
language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
sudo: required
before_install:
    - sudo apt-get install libneon27-dev
    - ./install_litmus.sh
install: pip install tox-travis
script: tox
